/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FortysevenCodetab {
        "dataLanguages": string | string[];
    }
}
declare global {
    interface HTMLFortysevenCodetabElement extends Components.FortysevenCodetab, HTMLStencilElement {
    }
    var HTMLFortysevenCodetabElement: {
        prototype: HTMLFortysevenCodetabElement;
        new (): HTMLFortysevenCodetabElement;
    };
    interface HTMLElementTagNameMap {
        "fortyseven-codetab": HTMLFortysevenCodetabElement;
    }
}
declare namespace LocalJSX {
    interface FortysevenCodetab {
        "dataLanguages"?: string | string[];
    }
    interface IntrinsicElements {
        "fortyseven-codetab": FortysevenCodetab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fortyseven-codetab": LocalJSX.FortysevenCodetab & JSXBase.HTMLAttributes<HTMLFortysevenCodetabElement>;
        }
    }
}
